version: '3.8'

services:
    node:
        image: 'node:lts'
        user: '${USER_ID:-1000}:${GROUP_ID:-1000}'
        environment:
            YARN_CACHE_FOLDER: '/home/node/.yarn'
        volumes:
            - './:/srv/game'
            - '${YARN_CACHE_FOLDER:-~/.cache/yarn}:/home/node/.yarn'
        working_dir: '/srv/game'
